<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AutoCADDir Condition="'$(TargetFramework)' == 'net48'">$(ProgramW6432)\Autodesk\AutoCAD 2022</AutoCADDir>
    <AutoCADDir Condition="'$(TargetFramework)' == 'net8.0-windows'">$(ProgramW6432)\Autodesk\AutoCAD 2025</AutoCADDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcCoreMgd"><HintPath>$(AutoCADDir)\accoremgd.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="AcDbMgd"><HintPath>$(AutoCADDir)\acdbmgd.dll</HintPath><Private>false</Private></Reference>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net48'" />
  </ItemGroup>
  <Target Name="StagePlugin" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)\..\PrepareXrefs-bin\$(TargetFramework)" />
  </Target>
</Project>
